### ISSUE TITLE
PLS

### ISSUE THREAD

**Issue by codemaster123puppy** [XOTlC/Blacket-Legacy#57]
Can you pls make a video on how to make a blooket private server just like blacket?🙏🥺 (With PHP)

**Comment by VillainsRule4000** [comment]
It's not something that just comes in one video.
Blacket took MONTHS.

**Comment by codemaster123puppy** [comment]
XOTIC PLS RESPOND😟

**Comment by codemaster123puppy** [comment]
I know, but is there a way to create a blooket private server with PHP.😳😳

**Comment by VillainsRule4000** [comment]
There is; Xotic did it.
It just can't be smashed into a video.

Do you even know PHP?
